### ISSUE TITLE
Add annotation `<json lowercase_tags>`

### ISSUE THREAD

**Issue by mjambon** [ahrefs/atd#106]
Json enums using lowercase strings are very common in the wild. ATD definitions often end up like this:
```ocaml
type my_enum = [
| Action <json name="action">
| Event <json name="event">
| Other_thing <json name="other_thing">
]
```
Instead, it would be handy and more readable to have just this:
```ocaml
type my_enum = [ Action | Event | Other_thing ] <json lowercase_tags>
```
This should be done after https://github.com/mjambon/atd/pull/72 gets merged.

**Comment by MisterDA** [comment]
I just had this problem an API, however they chose to use the hyphen `-` instead of the underscore `_` between words.
```ocaml
type my_enum = [
| Action <json name="action">
| Event <json name="event">
| Other_thing <json name="other-thing">
]
```

Maybe the separator could be a parameter of `lowercase_tags`?

I the same spirit, the API oddly uses `CamelCase` for its keys, maybe something like this could also be applied?

```ocaml
type my_record = {
   the_first_field <json name="TheFirstField">: string;
   the_second_field <json name="TheSecondField">: string;
}
```

could be written as

```ocaml
type my_record = {
   the_first_field: string;
   the second_field: string;
} <json camel_case>
```

It would be important to keep `json name` as an escape hatch for special cases.

**Comment by mjambon** [comment]
Having more options to easily map field names from ATD to JSON could be useful. The main issue is the work involved since it would have to be supported by all the target languages that support JSON (or at least fail if it's not implemented for a particular language).

Please create a new issue for this for easier tracking.
