### ISSUE TITLE
Support more languages?

### ISSUE THREAD

**Issue by aij** [ahrefs/atd#142]
I'm interested in using ATD with Scala, Flow (Flowtype/JS) , and Purescript.

I've used protobuf before, and really liked it in C++ and Python, though using the Java bindings from Scala was suboptimal. It was nice when they added union/sum types, but Protobuf 3.0 dropped support for required fields.

ATD seems like a better match for functional / strongly typed languages, but we are not (yet) using OCaml here, and it seems unlikely we would ever completely abandon Scala.

We're mostly using Scala server-side and JS+Flow+React client side, with a little Purescript thrown in, and folks have been spending a lot of time writing code to extract/create JSON objects and trying to keep them in sync with PropTypes / Flow types. Having using Protobuf, this seems like a silly thing to be wasting time and bugs on...

In order to gain adoption, we would at least need good Scala support. (I don't mind working on it.)

The ability to generate Flow type definitions from the same source would make ATD much more compelling.

Supporting Purescript (or at least knowing we could add support in the future) would be a cherry on top. :smiley:

In terms of planning, is the project at a stage where it would make sense to add more language support?

What should the relation between `atdj` and `atds` (`atdscala`?) be? We could make them completely independent, or they could share some code (it might make sense to use the same class/field/variant names), or should scala support be part of `atdj`? (Eg. via an optional flag) I could see other users (who might mix Scala and Java code more) wanting to use the same classes from both Scala and Java, though I'm not sure on the best way to support mixed Scala/Java use.

**Comment by mjambon** [comment]
> In terms of planning, is the project at a stage where it would make sense to add more language support?

Yes, absolutely. @rgrinberg is currently working on adding bucklescript support (#44). We recently merged multiple repos into a single `atd` repo, so it now includes both atdgen and atdj front-ends as well as the library for parsing atd files and some runtime libraries. The merge simplified releases and issue tracking. Everything is distributed as a single archive that serves as the source for multiple opam packages. This setup has been working well, so I'd recommend adding support for new languages to this repo rather than an external one.

The documentation is automatically built and published from the files in https://github.com/mjambon/atd/tree/master/doc, showing up at http://atd.readthedocs.io so you'd get this for free. Adding documentation for a new front-end is just a matter of writing it and committing it to git.

> What should the relation between atdj and atds (atdscala?) be?

I don't know enough about scala to have a strong opinion. atdj was developed independently from atdgen, which resulted in simpler code, and there have been no big downsides. I think it's a reasonable approach for a new target language. Now if you'd generate java code anyway and a scala interface for it, you could reuse and extend atdj.

Let us know if you're unsure how to get started. We've had requests for scala support in the past, so it would be awesome to have this.

**Comment by mjambon** [comment]
Note that I'm about to deliver Python support. Closing this issue because it's open-ended.
