### ISSUE TITLE
atdcat -jsonschema: add some additionalProperties: false

### ISSUE THREAD

**Issue by aryx** [ahrefs/atd#290]
It would be great if atdcat -jsonschema could add some additionalProperties:false when generating the jsonschema.
See for example https://github.com/returntocorp/semgrep-interfaces/pull/1/files#diff-8caf6d2b07931bf8cbff01b873c0e4c58510b101a86785406b016c680c5ab5a0

Note that this does not prevent to have extra fields in the JSON (which is something we want to tolerate).
This directive is more for the code generated for the interfaces.

The problem is more related to how the jsonschema 2 typescript (json2ts) work; without the additionalProperties: false, it generates code like
export interface Position {
  line: number;
  col: number;
  offset: number;
  [k: string]: unknown;
}
The code to read the JSON is good, it accepts extra fields, but then the interface allows also extra fields, so we don't get strict typing on the Typescript side. if you put the additionalProperties:false in the jsonschema, then json2ts does not add this [k: string]: unknown; at the end, but it is still tolerant to extra fields in the JSON.

**Comment by mjambon** [comment]
As indicated privately, nobody wants to reject input JSON data if it has extra fields that could be just ignored. These fields should be ignored and not cause an error. This is essential for compatibility with API upgrades. The addition of a new field to an object sent to a legacy client is not considered a breaking change.

Here's how JSON Schema interprets the 3 cases:
* JSON Schema validation without `additionalProperties` (ok): https://www.jsonschemavalidator.net/s/EMWEwhMF
* JSON Schema validation with `additionalProperties: true` (ok): https://www.jsonschemavalidator.net/s/Bpz9zMLY
* JSON Schema validation with `additionalProperties: false` (error): https://www.jsonschemavalidator.net/s/e2BAS3BM

The issue is with `json2ts`. Maybe it has an option to interpret the absence of `additionalProperties` as "please ignore extra fields AND don't let us create objects with extra fields".

There's just so much effort I'm willing to put into supporting external tools that rely on JSON Schema when we're already offering a tool that does the job (`atdts`).

**Comment by aryx** [comment]
yep, sounds like a bug in json2ts
